#!/usr/bin/env python

import sys

def output(document, defaultdescs, databaseversion, infilename, outfilename, lang, tag):

  def get_event_signature(element):
    sign = element["name"] + "("
    first = True
    if "params" in element:
      cnt = 1;
      for param in element["params"]:
        if first:
          first = False
        else:
          sign = sign + ", "
        sign = sign + param["type"] + " " + "${" + str(cnt) + ":" + param["name"] + "}"
        cnt += 1;
    sign = sign + ")"
    return sign

  def get_function_signature(element):
    sign = element["name"] + "("
    first = True
    if "params" in element:
      cnt = 1;
      for param in element["params"]:
        if first:
          first = False
        else:
          sign = sign + ", "
        sign = sign + "${" + str(cnt) + ":" + param["type"] + " " + param["name"] + "}"
        cnt += 1;
    sign = sign + ")"
    return sign

  constants = []
  events = []
  functions = []
  for element in document:
    if 'status' not in element or element['status'] == 'normal':
      if element["cat"] == "constant":
        constants.append(element)
      elif element["cat"] == "event":
        events.append(element)
      elif element["cat"] == "function":
        functions.append(element)

  if infilename is not None:
    inf = open(infilename, "r")
  else:
    inf = sys.stdin

  try:
    inputlines = inf.readlines()

  finally:
    if infilename is not None:
      inf.close()

  if outfilename is not None:
    outf = open(outfilename, "w")
  else:
    outf = sys.stdout

  try:
    for line in inputlines:
      if line.startswith("<<< CONSTANTS >>>"):
        for entry in constants:
          outf.write("&print_snippet($template, 'constants', $description, '" + entry["name"]
            + "', '', '" + entry["type"] + "');\n")
      elif line.startswith("<<< EVENTS >>>"):
        for entry in events:
          outf.write("&print_snippet($template, 'events', $description, '" + entry["name"] 
            + "', '" + get_event_signature(entry) + "');\n")
      elif line.startswith("<<< FUNCTIONS >>>"):
        for entry in functions:
          returntype = entry["type"] if entry.has_key("type") else "void"
          outf.write("&print_snippet($template, 'functions', $description, '" + entry["name"]
            + "', '" + get_function_signature(entry) + "','" + returntype + "');\n")
      elif line.startswith("<<< DESCRIPTION >>>"):
        outf.write("my $description = 'Generated by LSL2 Derived Files Generator. Database version: %s';\n"
          % (databaseversion))
      else:
        outf.write(line)

  finally:
    if outfilename is not None:
      outf.close()

      # output for this function is perl script.
      # usually this function is called without outfilename, hence written in sysout.
      # after then perl will execute the contents in outf.

pass
